// ENHANCED MASTER DATA & THEME CONFIG
export const MASTER_DATA = {
  vendors: {
    portnox: {
      name: "Portnox CLEAR",
      shortName: "Portnox",
      color: "#00F5D4",
      architecture: "Cloud-Native",
      security: { zeroTrustScore: 98, threatDetection: 95, mttr: 0.1 },
      metrics: { deploymentTime: 0.5, fteRequired: 0.2 },
      pricing: { model: "subscription", basePrice: 4 },
      costs: { hardware: 0, implementation: 5000, personnelPerYear: 21250 },
      features: {
        iot: 95,
        guest: 98,
        tacacs: 90,
        conditionalAccess: 100,
        mfa: 100,
        deviceTrust: 98,
        radius: 100,
        certAuth: 100,
      },
      compliance: {
        hipaa: 98,
        pci: 99,
        sox: 97,
        nist: 98,
        gdpr: 97,
        iso27001: 98,
        fedramp: 95,
        cmmc: 96,
        nerc: 94,
        ferpa: 96,
        ccpa: 97,
        glba: 96,
        fisma: 95,
        hitech: 98,
      },
    },
    cisco: {
      name: "Cisco ISE",
      shortName: "Cisco",
      color: "#00bceb",
      architecture: "On-Premises",
      security: { zeroTrustScore: 75, threatDetection: 70, mttr: 8 },
      metrics: { deploymentTime: 90, fteRequired: 1.5 },
      pricing: { model: "perpetual", basePrice: 60 },
      costs: { hardware: 120000, implementation: 75000, personnelPerYear: 127500 },
      features: {
        iot: 80,
        guest: 90,
        tacacs: 100,
        conditionalAccess: 70,
        mfa: 85,
        deviceTrust: 80,
        radius: 100,
        certAuth: 90,
      },
      compliance: {
        hipaa: 85,
        pci: 90,
        sox: 88,
        nist: 92,
        gdpr: 85,
        iso27001: 90,
        fedramp: 88,
        cmmc: 85,
        nerc: 90,
        ferpa: 85,
        ccpa: 83,
        glba: 87,
        fisma: 89,
        hitech: 86,
      },
    },
    aruba: {
      name: "Aruba ClearPass",
      shortName: "Aruba",
      color: "#ff6900",
      architecture: "On-Premises",
      security: { zeroTrustScore: 72, threatDetection: 65, mttr: 10 },
      metrics: { deploymentTime: 75, fteRequired: 1.2 },
      pricing: { model: "perpetual", basePrice: 55 },
      costs: { hardware: 85000, implementation: 65000, personnelPerYear: 102000 },
      features: {
        iot: 85,
        guest: 95,
        tacacs: 60,
        conditionalAccess: 65,
        mfa: 90,
        deviceTrust: 82,
        radius: 100,
        certAuth: 92,
      },
      compliance: {
        hipaa: 88,
        pci: 92,
        sox: 85,
        nist: 90,
        gdpr: 86,
        iso27001: 88,
        fedramp: 85,
        cmmc: 83,
        nerc: 87,
        ferpa: 86,
        ccpa: 85,
        glba: 86,
        fisma: 87,
        hitech: 87,
      },
    },
    fortinet: {
      name: "Fortinet FortiNAC",
      shortName: "Fortinet",
      color: "#ee3124",
      architecture: "On-Premises",
      security: { zeroTrustScore: 68, threatDetection: 75, mttr: 12 },
      metrics: { deploymentTime: 60, fteRequired: 1.0 },
      pricing: { model: "perpetual", basePrice: 45 },
      costs: { hardware: 60000, implementation: 40000, personnelPerYear: 85000 },
      features: {
        iot: 90,
        guest: 80,
        tacacs: 80,
        conditionalAccess: 60,
        mfa: 80,
        deviceTrust: 75,
        radius: 100,
        certAuth: 80,
      },
      compliance: {
        hipaa: 80,
        pci: 85,
        sox: 82,
        nist: 88,
        gdpr: 82,
        iso27001: 85,
        fedramp: 82,
        cmmc: 80,
        nerc: 85,
        ferpa: 81,
        ccpa: 80,
        glba: 82,
        fisma: 84,
        hitech: 81,
      },
    },
    forescout: {
      name: "Forescout Platform",
      shortName: "Forescout",
      color: "#7a2a90",
      architecture: "On-Premises",
      security: { zeroTrustScore: 80, threatDetection: 85, mttr: 6 },
      metrics: { deploymentTime: 120, fteRequired: 1.8 },
      pricing: { model: "perpetual", basePrice: 70 },
      costs: { hardware: 150000, implementation: 90000, personnelPerYear: 153000 },
      features: {
        iot: 100,
        guest: 85,
        tacacs: 50,
        conditionalAccess: 75,
        mfa: 80,
        deviceTrust: 88,
        radius: 100,
        certAuth: 85,
      },
      compliance: {
        hipaa: 90,
        pci: 88,
        sox: 86,
        nist: 94,
        gdpr: 88,
        iso27001: 91,
        fedramp: 89,
        cmmc: 87,
        nerc: 91,
        ferpa: 88,
        ccpa: 87,
        glba: 88,
        fisma: 90,
        hitech: 89,
      },
    },
    packetfence: {
      name: "PacketFence",
      shortName: "PacketFence",
      color: "#f0ad4e",
      architecture: "On-Premises",
      security: { zeroTrustScore: 60, threatDetection: 50, mttr: 24 },
      metrics: { deploymentTime: 100, fteRequired: 2.0 },
      pricing: { model: "open-source", basePrice: 0 },
      costs: { hardware: 50000, implementation: 100000, personnelPerYear: 170000 },
      features: {
        iot: 70,
        guest: 80,
        tacacs: 85,
        conditionalAccess: 50,
        mfa: 70,
        deviceTrust: 65,
        radius: 100,
        certAuth: 80,
      },
      compliance: {
        hipaa: 60,
        pci: 65,
        sox: 62,
        nist: 70,
        gdpr: 65,
        iso27001: 68,
        fedramp: 60,
        cmmc: 58,
        nerc: 65,
        ferpa: 62,
        ccpa: 60,
        glba: 62,
        fisma: 65,
        hitech: 61,
      },
    },
    ivanti: {
      name: "Ivanti Neurons for ZTA",
      shortName: "Ivanti",
      color: "#008c95",
      architecture: "Cloud-Managed",
      security: { zeroTrustScore: 82, threatDetection: 80, mttr: 4 },
      metrics: { deploymentTime: 30, fteRequired: 0.6 },
      pricing: { model: "subscription", basePrice: 18 },
      costs: { hardware: 10000, implementation: 25000, personnelPerYear: 51000 },
      features: {
        iot: 75,
        guest: 88,
        tacacs: 40,
        conditionalAccess: 85,
        mfa: 95,
        deviceTrust: 90,
        radius: 100,
        certAuth: 90,
      },
      compliance: {
        hipaa: 90,
        pci: 85,
        sox: 88,
        nist: 91,
        gdpr: 89,
        iso27001: 90,
        fedramp: 87,
        cmmc: 85,
        nerc: 88,
        ferpa: 88,
        ccpa: 88,
        glba: 87,
        fisma: 88,
        hitech: 89,
      },
    },
    extreme: {
      name: "ExtremeControl",
      shortName: "Extreme",
      color: "#682a7d",
      architecture: "On-Premises",
      security: { zeroTrustScore: 65, threatDetection: 60, mttr: 14 },
      metrics: { deploymentTime: 80, fteRequired: 1.1 },
      pricing: { model: "perpetual", basePrice: 50 },
      costs: { hardware: 75000, implementation: 50000, personnelPerYear: 93500 },
      features: {
        iot: 82,
        guest: 85,
        tacacs: 70,
        conditionalAccess: 60,
        mfa: 75,
        deviceTrust: 70,
        radius: 100,
        certAuth: 80,
      },
      compliance: {
        hipaa: 75,
        pci: 80,
        sox: 78,
        nist: 82,
        gdpr: 78,
        iso27001: 80,
        fedramp: 75,
        cmmc: 73,
        nerc: 80,
        ferpa: 76,
        ccpa: 75,
        glba: 77,
        fisma: 78,
        hitech: 76,
      },
    },
    juniper: {
      name: "Juniper Mist",
      shortName: "Juniper",
      color: "#84bd00",
      architecture: "Cloud-Managed",
      security: { zeroTrustScore: 79, threatDetection: 88, mttr: 5 },
      metrics: { deploymentTime: 25, fteRequired: 0.5 },
      pricing: { model: "subscription", basePrice: 22 },
      costs: { hardware: 30000, implementation: 25000, personnelPerYear: 42500 },
      features: {
        iot: 88,
        guest: 90,
        tacacs: 30,
        conditionalAccess: 80,
        mfa: 92,
        deviceTrust: 85,
        radius: 100,
        certAuth: 95,
      },
      compliance: {
        hipaa: 85,
        pci: 88,
        sox: 84,
        nist: 90,
        gdpr: 87,
        iso27001: 88,
        fedramp: 85,
        cmmc: 83,
        nerc: 87,
        ferpa: 85,
        ccpa: 85,
        glba: 85,
        fisma: 86,
        hitech: 85,
      },
    },
    arista: {
      name: "Arista AGNI",
      shortName: "Arista",
      color: "#ff7f00",
      architecture: "Cloud-Managed",
      security: { zeroTrustScore: 78, threatDetection: 82, mttr: 6 },
      metrics: { deploymentTime: 28, fteRequired: 0.6 },
      pricing: { model: "subscription", basePrice: 25 },
      costs: { hardware: 40000, implementation: 30000, personnelPerYear: 51000 },
      features: {
        iot: 85,
        guest: 88,
        tacacs: 35,
        conditionalAccess: 78,
        mfa: 90,
        deviceTrust: 84,
        radius: 100,
        certAuth: 90,
      },
      compliance: {
        hipaa: 82,
        pci: 86,
        sox: 83,
        nist: 89,
        gdpr: 85,
        iso27001: 86,
        fedramp: 83,
        cmmc: 81,
        nerc: 85,
        ferpa: 83,
        ccpa: 83,
        glba: 84,
        fisma: 84,
        hitech: 83,
      },
    },
    microsoft: {
      name: "Microsoft NPS",
      shortName: "Microsoft",
      color: "#00a4ef",
      architecture: "On-Premises",
      security: { zeroTrustScore: 45, threatDetection: 30, mttr: 48 },
      metrics: { deploymentTime: 45, fteRequired: 0.8 },
      pricing: { model: "included", basePrice: 5 },
      costs: { hardware: 20000, implementation: 15000, personnelPerYear: 68000 },
      features: {
        iot: 30,
        guest: 40,
        tacacs: 20,
        conditionalAccess: 50,
        mfa: 100,
        deviceTrust: 60,
        radius: 100,
        certAuth: 70,
      },
      compliance: {
        hipaa: 50,
        pci: 55,
        sox: 60,
        nist: 65,
        gdpr: 60,
        iso27001: 62,
        fedramp: 55,
        cmmc: 50,
        nerc: 58,
        ferpa: 55,
        ccpa: 55,
        glba: 57,
        fisma: 58,
        hitech: 52,
      },
    },
    securew2: {
      name: "SecureW2",
      shortName: "SecureW2",
      color: "#2c5aa0",
      architecture: "Cloud-Native",
      security: { zeroTrustScore: 85, threatDetection: 70, mttr: 3 },
      metrics: { deploymentTime: 7, fteRequired: 0.3 },
      pricing: { model: "subscription", basePrice: 8 },
      costs: { hardware: 0, implementation: 8000, personnelPerYear: 25500 },
      features: {
        iot: 60,
        guest: 85,
        tacacs: 20,
        conditionalAccess: 70,
        mfa: 95,
        deviceTrust: 80,
        radius: 100,
        certAuth: 100,
      },
      compliance: {
        hipaa: 80,
        pci: 85,
        sox: 82,
        nist: 88,
        gdpr: 83,
        iso27001: 85,
        fedramp: 80,
        cmmc: 78,
        nerc: 82,
        ferpa: 82,
        ccpa: 82,
        glba: 82,
        fisma: 83,
        hitech: 81,
      },
    },
    foxpass: {
      name: "Foxpass",
      shortName: "Foxpass",
      color: "#d62929",
      architecture: "Cloud-Native",
      security: { zeroTrustScore: 70, threatDetection: 60, mttr: 5 },
      metrics: { deploymentTime: 2, fteRequired: 0.25 },
      pricing: { model: "subscription", basePrice: 6 },
      costs: { hardware: 0, implementation: 5000, personnelPerYear: 21250 },
      features: {
        iot: 50,
        guest: 70,
        tacacs: 75,
        conditionalAccess: 60,
        mfa: 90,
        deviceTrust: 70,
        radius: 100,
        certAuth: 75,
      },
      compliance: {
        hipaa: 70,
        pci: 75,
        sox: 72,
        nist: 78,
        gdpr: 73,
        iso27001: 75,
        fedramp: 70,
        cmmc: 68,
        nerc: 72,
        ferpa: 71,
        ccpa: 71,
        glba: 72,
        fisma: 73,
        hitech: 71,
      },
    },
    meraki: {
      name: "Meraki Access Control",
      shortName: "Meraki",
      color: "#85c03c",
      architecture: "Cloud-Managed",
      security: { zeroTrustScore: 68, threatDetection: 65, mttr: 12 },
      metrics: { deploymentTime: 1, fteRequired: 0.4 },
      pricing: { model: "included", basePrice: 15 },
      costs: { hardware: 0, implementation: 10000, personnelPerYear: 34000 },
      features: {
        iot: 70,
        guest: 92,
        tacacs: 10,
        conditionalAccess: 65,
        mfa: 100,
        deviceTrust: 75,
        radius: 100,
        certAuth: 80,
      },
      compliance: {
        hipaa: 72,
        pci: 80,
        sox: 75,
        nist: 80,
        gdpr: 76,
        iso27001: 78,
        fedramp: 72,
        cmmc: 70,
        nerc: 75,
        ferpa: 73,
        ccpa: 73,
        glba: 74,
        fisma: 75,
        hitech: 73,
      },
    },
  },
  industries: {
    healthcare: {
      name: "Healthcare",
      icon: "🏥",
      breachCost: 11000000,
      riskMultiplier: 1.8,
      primaryStandards: ["HIPAA", "HITECH", "ISO 27001"],
      secondaryStandards: ["NIST", "CCPA"],
      keyRequirements: ["PHI protection", "Audit trails", "Encryption", "Access controls"],
    },
    finance: {
      name: "Financial Services",
      icon: "🏦",
      breachCost: 6000000,
      riskMultiplier: 2.0,
      primaryStandards: ["PCI-DSS", "SOX", "GLBA"],
      secondaryStandards: ["Basel III", "ISO 27001"],
      keyRequirements: ["Transaction security", "Data retention", "Audit compliance", "Fraud prevention"],
    },
    government: {
      name: "Government",
      icon: "🏛️",
      breachCost: 5000000,
      riskMultiplier: 1.5,
      primaryStandards: ["FedRAMP", "FISMA", "CMMC"],
      secondaryStandards: ["StateRAMP", "NIST"],
      keyRequirements: ["Zero trust architecture", "Continuous monitoring", "Supply chain security"],
    },
    manufacturing: {
      name: "Manufacturing",
      icon: "🏭",
      breachCost: 4500000,
      riskMultiplier: 1.4,
      primaryStandards: ["ISO 27001", "NIST", "IEC 62443"],
      secondaryStandards: ["TISAX"],
      keyRequirements: ["OT/IT convergence", "Supply chain", "IP protection"],
    },
    retail: {
      name: "Retail",
      icon: "🛍️",
      breachCost: 3300000,
      riskMultiplier: 1.3,
      primaryStandards: ["PCI-DSS", "CCPA", "SOC 2"],
      secondaryStandards: ["ISO 27001", "GDPR"],
      keyRequirements: ["Payment security", "Customer data", "Multi-location"],
    },
    education: {
      name: "Education",
      icon: "🎓",
      breachCost: 3900000,
      riskMultiplier: 1.1,
      primaryStandards: ["FERPA", "COPPA"],
      secondaryStandards: ["GDPR", "CCPA"],
      keyRequirements: ["Student data protection", "Access controls", "Remote learning"],
    },
    technology: {
      name: "Technology",
      icon: "💻",
      breachCost: 5500000,
      riskMultiplier: 1.2,
      primaryStandards: ["SOC 2", "ISO 27001"],
      secondaryStandards: ["GDPR", "CCPA"],
      keyRequirements: ["Data sovereignty", "API security", "Cloud security"],
    },
    energy: {
      name: "Energy/Utilities",
      icon: "⚡",
      breachCost: 4800000,
      riskMultiplier: 1.6,
      primaryStandards: ["NERC CIP", "IEC 62443"],
      secondaryStandards: ["ISO 27001", "NIST"],
      keyRequirements: ["Critical infrastructure", "SCADA security", "Grid resilience"],
    },
    pharmaceuticals: {
      name: "Pharmaceuticals",
      icon: "💊",
      breachCost: 5200000,
      riskMultiplier: 1.7,
      primaryStandards: ["FDA 21 CFR Part 11", "HIPAA"],
      secondaryStandards: ["GxP", "ISO 27001"],
      keyRequirements: ["Electronic records", "Validation", "Clinical trial data"],
    },
    telecommunications: {
      name: "Telecommunications",
      icon: "📡",
      breachCost: 4000000,
      riskMultiplier: 1.3,
      primaryStandards: ["CPNI", "GDPR"],
      secondaryStandards: ["ISO 27001", "PCI-DSS"],
      keyRequirements: ["Customer data", "Network security", "5G security"],
    },
    legal: {
      name: "Legal Services",
      icon: "⚖️",
      breachCost: 3500000,
      riskMultiplier: 1.2,
      primaryStandards: ["ABA Model Rules"],
      secondaryStandards: ["GDPR", "CCPA"],
      keyRequirements: ["Client confidentiality", "Data retention", "Privilege protection"],
    },
    insurance: {
      name: "Insurance",
      icon: "🛡️",
      breachCost: 4200000,
      riskMultiplier: 1.4,
      primaryStandards: ["NAIC Model Laws"],
      secondaryStandards: ["HIPAA", "PCI-DSS"],
      keyRequirements: ["Claims data", "PII protection", "Risk assessment"],
    },
  },
  compliance: {
    hipaa: {
      name: "HIPAA",
      fullName: "Health Insurance Portability and Accountability Act",
      controls: 54,
      category: "Healthcare",
      description: "Protects patient health information",
    },
    pci: {
      name: "PCI DSS 4.0",
      fullName: "Payment Card Industry Data Security Standard",
      controls: 12,
      category: "Financial",
      description: "Secures payment card data",
    },
    sox: {
      name: "SOX",
      fullName: "Sarbanes-Oxley Act",
      controls: 20,
      category: "Financial",
      description: "Financial reporting requirements",
    },
    nist: {
      name: "NIST 800-53",
      fullName: "NIST Special Publication 800-53",
      controls: 250,
      category: "Federal",
      description: "Security and privacy controls",
    },
    gdpr: {
      name: "GDPR",
      fullName: "General Data Protection Regulation",
      controls: 99,
      category: "Privacy",
      description: "EU data protection regulation",
    },
    iso27001: {
      name: "ISO 27001",
      fullName: "ISO/IEC 27001:2022",
      controls: 93,
      category: "International",
      description: "Information security management",
    },
    fedramp: {
      name: "FedRAMP",
      fullName: "Federal Risk and Authorization Management Program",
      controls: 325,
      category: "Federal",
      description: "Cloud security for government",
    },
    cmmc: {
      name: "CMMC",
      fullName: "Cybersecurity Maturity Model Certification",
      controls: 110,
      category: "Defense",
      description: "DoD contractor requirements",
    },
    nerc: {
      name: "NERC CIP",
      fullName: "North American Electric Reliability Corporation Critical Infrastructure Protection",
      controls: 45,
      category: "Energy",
      description: "Electric grid security",
    },
    ferpa: {
      name: "FERPA",
      fullName: "Family Educational Rights and Privacy Act",
      controls: 12,
      category: "Education",
      description: "Student records privacy",
    },
    ccpa: {
      name: "CCPA",
      fullName: "California Consumer Privacy Act",
      controls: 20,
      category: "Privacy",
      description: "California privacy rights",
    },
    glba: {
      name: "GLBA",
      fullName: "Gramm-Leach-Bliley Act",
      controls: 16,
      category: "Financial",
      description: "Financial privacy protection",
    },
    fisma: {
      name: "FISMA",
      fullName: "Federal Information Security Management Act",
      controls: 171,
      category: "Federal",
      description: "Federal agency security",
    },
    hitech: {
      name: "HITECH",
      fullName: "Health Information Technology for Economic and Clinical Health Act",
      controls: 25,
      category: "Healthcare",
      description: "Electronic health records",
    },
  },
  organizationSizes: [
    {
      id: "small",
      size: "Small Business",
      users: "1-100",
      budget: "$10K-50K/year",
      complexity: "Basic",
      deviceRange: [100, 500],
      complianceNeeds: 1,
    },
    {
      id: "midmarket",
      size: "Mid-Market",
      users: "100-1,000",
      budget: "$50K-250K/year",
      complexity: "Moderate",
      deviceRange: [500, 2500],
      complianceNeeds: 3,
    },
    {
      id: "enterprise",
      size: "Enterprise",
      users: "1,000-10,000",
      budget: "$250K-1M/year",
      complexity: "High",
      deviceRange: [2500, 10000],
      complianceNeeds: 5,
    },
    {
      id: "global",
      size: "Global Enterprise",
      users: "10,000+",
      budget: "$1M+/year",
      complexity: "Very High",
      deviceRange: [10000, 50000],
      complianceNeeds: 10,
    },
  ],
}

export const NIVO_THEME = {
  background: "transparent",
  textColor: "rgb(var(--foreground-rgb))",
  fontSize: 12,
  axis: {
    domain: { line: { stroke: "rgba(var(--card-border-rgb), 0.8)", strokeWidth: 1 } },
    ticks: {
      line: { stroke: "rgba(var(--card-border-rgb), 0.8)", strokeWidth: 1 },
      text: { fill: "rgb(var(--foreground-rgb), 0.8)" },
    },
    legend: { text: { fill: "rgb(var(--foreground-rgb))", fontSize: 14, fontWeight: 600 } },
  },
  grid: { line: { stroke: "rgba(var(--card-border-rgb), 0.3)", strokeDasharray: "4 4" } },
  tooltip: {
    container: {
      background: "rgba(var(--card-rgb), 0.95)",
      color: "rgb(var(--foreground-rgb))",
      border: "1px solid rgba(var(--card-border-rgb), 0.8)",
      backdropFilter: "blur(10px)",
      borderRadius: "8px",
      padding: "12px",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.4)",
    },
  },
  legends: { text: { fill: "rgb(var(--foreground-rgb), 0.9)", fontSize: 12 } },
  annotations: {
    text: {
      fontSize: 13,
      fill: "rgb(var(--foreground-rgb))",
      outlineWidth: 2,
      outlineColor: "rgba(var(--background-rgb), 0.8)",
    },
    link: { stroke: "rgba(var(--primary-rgb), 0.5)", strokeWidth: 1 },
    outline: {
      stroke: "rgba(var(--primary-rgb), 0.5)",
      strokeWidth: 2,
      outlineWidth: 3,
      outlineColor: "rgba(var(--background-rgb), 0.8)",
    },
    symbol: {
      fill: "rgba(var(--primary-rgb), 0.5)",
      outlineWidth: 2,
      outlineColor: "rgba(var(--background-rgb), 0.8)",
    },
  },
}
